AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0f403e3180720dd7e'  
      InstanceType: 't2.micro'  # Tipo de instancia EC2
      SecurityGroups:
        - Ref: WebAccessSecurityGroup
        - Ref: SSHAccessSecurityGroup
      BlockDeviceMappings:
        - DeviceName: '/dev/sda1'
          Ebs:
            VolumeSize: 20
            VolumeType: 'gp3'  # Tipo de volumen EBS gp3

  WebAccessSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for web access'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'  # Acceso desde cualquier parte
        - IpProtocol: 'tcp'
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'  # Acceso desde cualquier parte

  SSHAccessSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for SSH access'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
          CidrIp: '186.84.90.70/32'  # Reemplaza 'your_ip_address' con tu dirección IP pública
